

set nocompatible

" Switch syntax highlighting on
let python_highlight_all=1
syntax on
set encoding=utf-8
set t_Co=256

" Set statusline
set rtp+=/usr/local/lib/python2.7/dist-packages/powerline/bindings/vim/
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
 
" Enable file type detection and do language-dependent indenting.
filetype off
execute pathogen#infect()
call pathogen#helptags()
filetype plugin indent on

colorscheme anotherdark

" Appearance
set relativenumber
set laststatus=2
set wrap
set linebreak
set textwidth=79
set colorcolumn=80

" Behavior
set backspace=indent,eol,start
set history=50
set incsearch
set hlsearch
set fileformat=unix

" Indentation
set autoindent
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

" Folding
set foldmethod=marker
nnoremap <space> za

" Use the below highlight group when displaying bad whitespace is desired.
highlight BadWhitespace ctermbg=red guibg=red
" Display tabs at the beginning of a line in Python mode as bad.
au BufRead,BufNewFile *.py,*.pyw match BadWhitespace /^\t\+/
" Make trailing whitespace be flagged as bad.
 au BufRead,BufNewFile *.py,*.pyw,*.c,*.h match BadWhitespace /\s\+$/

" Tab-completion in command-line mode
set wildmode=full
set wildmenu

" Disable the arrow keys in normal and insert mode. Leave for visual mode.
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>

" Disable the help key.
inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>

"------------------------------------------"
"   NERD Tree Plugin Settings
"------------------------------------------"
""" Toggle the NERD Tree on and off with F7
nmap <F7> :NERDTreeToggle<CR>

""" Close the NERD Tree with Shift-F7
nmap <S-F7> :NERDTreeClose<CR>

" Show the bookmarks table on startup
let NERDTreeShowBookmarks=1

" Don't display these kinds of files
let NERDTreeIgnore=[ '\.ncb$', '\.suo$', '\.vcproj\.RIMNET', '\.obj$',
                   \ '\.ilk$', '^BuildLog.htm$', '\.pdb$', '\.idb$',
                   \ '\.embed\.manifest$', '\.embed\.manifest.res$',
                   \  '\.intermediate\.manifest$', '^mt.deps' ]

map,r :NERDTreeFind<CR>

" -----------------------------------------" 
"   syntastic plugin settings
" -----------------------------------------"
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0


" temp file locations. make sure subdirectories are created in ~/tmp
set undodir=~/tmp/.undo//
set backupdir=~/tmp/.backup//
set directory=~/tmp/.swp//
""
