" Use Vim settings, rather than Vi settings (much better!).
" " This must be first, because it changes other options as a side effect
set nocompatible
"
" Make backspace behave in a sane manner.
set backspace=indent,eol,start
" Switch syntax highlighting on
syntax on
""""
" " Enable file type detection and do language-dependent indenting.
filetype off
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()
filetype plugin indent on
"
"
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
"
set encoding=utf-8
set relativenumber
"
set wrap
set textwidth=79
set colorcolumn=80
"
" The following eight commands disable the arrow keys.
"
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
"
" The following 3 lines disable the help key.
"
inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>

"-----------------------------------------------------------------------------
""" NERD Tree Plugin Settings
"-----------------------------------------------------------------------------
""" Toggle the NERD Tree on an off with F7
nmap <F7> :NERDTreeToggle<CR>

" Close the NERD Tree with Shift-F7
nmap <S-F7> :NERDTreeClose<CR>
"
" Show the bookmarks table on startup
let NERDTreeShowBookmarks=1
"
" Don't display these kinds of files
let NERDTreeIgnore=[ '\.ncb$', '\.suo$', '\.vcproj\.RIMNET', '\.obj$',
                   \ '\.ilk$', '^BuildLog.htm$', '\.pdb$', '\.idb$',
                   \ '\.embed\.manifest$', '\.embed\.manifest.res$',
                   \  '\.intermediate\.manifest$', '^mt.deps' ]

map,r :NERDTreeFind<CR>
