set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set nocompatible
"filetype plugin on
"filetype off
execute pathogen#infect()
syntax on
filetype plugin indent on
"
"http://stevelosh.com/blog/2010/09/coming-home-to-vim/#making-vim-more-useful
"
set encoding=utf-8
set scrolloff=3
set autoindent
set showmode
set showcmd
set hidden
set wildmenu
set wildmode=list:longest
set visualbell
set cursorline
set ttyfast
set ruler
set backspace=indent,eol,start
set laststatus=2
set relativenumber
set undofile
"
" let mapleader = ","
"
nnoremap / /\v
vnoremap / /\v
set ignorecase
set smartcase
set gdefault
set incsearch
set showmatch
set hlsearch
"The <leader><space> mapping makes it easy to clear out a search by typing ,<space>.
" nnoremap <leader><space> :noh<cr>
nnoremap <tab> %
vnoremap <tab> %
"
"
set wrap
set textwidth=79
set formatoptions=qrn1
set colorcolumn=80
"
" The following eight commands disable the arrow keys.
"
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
nnoremap j gj
nnoremap k gk
"
" The following 3 lines disable the help key.
"
inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>
"
au FocusLost * :wa
"
" The following maps "jk" to the ESC key
"
inoremap jk <ESC>
" Let's make it easy to edit this file (mnemonic for the key sequence is
" 'e'dit 'v'imrc)
nmap <silent> ,ev :e $MYVIMRC<cr>

" And to source this file as well (mnemonic for the key sequence is
" 's'ource 'v'imrc)
nmap <silent> ,sv :so $MYVIMRC<cr>
" Set the status line the way I stole it from
" https://github.com/aleksmaus/vim-config/blob/master/.vimrc
set stl=%f\ %m\ %r%{fugitive#statusline()}\ Line:%l/%L[%p%%]\ Col:%v\ Buf:#%n\ [%b][0x%B]

" http://stackoverflow.com/questions/5375240/a-more-useful-statusline-in-vim
"set statusline=
"set statusline+=%7*\[%n]                                    "buffernr
""set statusline+=%1*\ %<%F\                                  "File+path
"set statusline+=%2*\ %y\                                    "FileType
"set statusline+=%3*\ %{''.(&fenc!=''?&fenc:&enc).''}        "Encoding
"set statusline+=%3*\ %{(&bomb?\",BOM\":\"\")}\              "Encoding2
"set statusline+=%4*\ %{&ff}\                                "FileFormat (dos/unix..)
"set statusline+=%5*\ %{&spelllang}\%{HighlightSearch()}\    "Spellanguage & Highlight on?
"set statusline+=%8*\ %=\ row:%l/%L\ (%03p%%)\               "Rownumber/total (%)
"set statusline+=%9*\ col:%03c\                              "Column number
"set statusline+=%0*\ \ %m%r%w\ %P\ \                        "Modified? Readonly? Top/bot.

"function! HighlightSearch()
"    if &hls
"        return 'H'
"    else
"        return ''
"    endif
"endfunction

" colors adapted from ligh2011.vim
"hi User1 guifg=#ffdad8 guibg=#880c0e
"hi User2 guifg=#000000 guibg=#F4905C
"hi User3 guifg=#112605 guibg=#f4f597
"hi User4 guifg=#051d00 guibg=#aefe7B
"hi User5 guifg=#ffffff guibg=#7dcc7d
"hi User7 guifg=#ffffff guibg=#880c0e gui=bold
"hi User8 guifg=#ffffff guibg=#5b7fbb
"hi User9 guifg=#ffffff guibg=#810085
"hi User0 guifg=#ffffff guibg=#094afe

"-----------------------------------------------------------------------------
"" NERD Tree Plugin Settings
"-----------------------------------------------------------------------------
"" Toggle the NERD Tree on an off with F7
nmap <F7> :NERDTreeToggle<CR>

" Close the NERD Tree with Shift-F7
nmap <S-F7> :NERDTreeClose<CR>
"
" Show the bookmarks table on startup
let NERDTreeShowBookmarks=1
"
" Don't display these kinds of files
let NERDTreeIgnore=[ '\.ncb$', '\.suo$', '\.vcproj\.RIMNET', '\.obj$',
                   \ '\.ilk$', '^BuildLog.htm$', '\.pdb$', '\.idb$',
                   \ '\.embed\.manifest$', '\.embed\.manifest.res$',
                   \ '\.intermediate\.manifest$', '^mt.deps' ]
"                                                          
map,r :NERDTreeFind<CR>
