# ========================================================================= #
#
# Personal $HOME/.zshrc file
# Author: Kevin Bowen <kevinbowen@protonmail.com>
# Version: 0.0.1
# Source : http://codeberg.org/kevinbowen/dotfiles
# Created: 20260701
# Last modified: 20260706
#
# ========================================================================= #

# https://blog.askesis.pl/post/2017/04/how-to-debug-zsh-startup-time.html
# zmodload zsh/zprof

# Disable unnecessary oh-my-zsh functions
DISABLE_AUTO_UPDATE="true"
DISABLE_MAGIC_FUNCTIONS="true"
DISABLE_COMPFIX="true"

# Smarter completion initialization
autoload -Uz compinit
if [ "$(date +'%j')" != "$(stat -f '%Sm' -t '%j' ~/.zcompdump 2>/dev/null)" ]; then
    compinit
else
    compinit -C
fi

# test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Path to Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"
export PATH="$PYENV_ROOT/bin:$PATH"

# Set name of the theme to load
ZSH_THEME="agnoster"

# How often to auto-update oh-my-zsh(in days).
zstyle ':omz:update' frequency 14

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# History control

export SAVEHIST=10000
export HISTSIZE=50000
# Save 10,000,000 lines of history to disk (will have to grep ~/.bash_history for full listing)

setopt EXTENDED_HISTORY          # Write the history file in the ':start:elapsed;command' format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire a duplicate event first when trimming history.
setopt HIST_IGNORE_DUPS          # Do not record an event that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete an old recorded event if a new event is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a previously found event.
setopt HIST_IGNORE_SPACE         # Do not record an event starting with a space.
setopt HIST_SAVE_NO_DUPS         # Do not write a duplicate event to the history file.
setopt HIST_VERIFY               # Do not execute immediately upon history expansion.
setopt APPEND_HISTORY            # append to history file
setopt HIST_NO_STORE             # Don't store history commands
# Ignore specific commands
export HISTIGNORE="cd:cd -:cl:docstart:docstop:exit:gits:ghic:ghil:gitp:hist:history:killwolf:la:ls:ll:mlb:pip-check:pipx-outdated:playball:ps:pwd:pyenv:run:sourceb"
HIST_STAMPS="$(echo -e "${CYAN}")[%d/%m %H:%M:%S]$(echo -e "${PURPLE}") "

# Plugins
# Custom plugins ard installed to $ZSH_CUSTOM/plugins/
plugins=(
  git
  vi-mode
  zsh-syntax-highlighting  # Always listed last!
)

# vi-mode plugin settings
VI_MODE_RESET_PROMPT_ON_MODE_CHANGE=true
VI_MODE_SET_CURSOR=true

VI_MODE_CURSOR_NORMAL=3
VI_MODE_CURSOR_VISUAL=6
VI_MODE_CURSOR_INSERT=2
VI_MODE_CURSOR_OPPEND=0

source $ZSH/oh-my-zsh.sh

# ========================================================================= #
#   User Configuration
# ========================================================================= #

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Compilation flags
# export ARCHFLAGS="-arch $(uname -m)"

# For colorizing man and info pages
LESS_TERMCAP_mb=$(printf "\e[01;31m") # enter blinking mode(bold red)
export LESS_TERMCAP_mb
LESS_TERMCAP_md=$(printf '\e[01;38;5;75m') # enter double-bright mode
export LESS_TERMCAP_md
LESS_TERMCAP_me=$(printf "\e[0m") # turn off all appearance modes
export LESS_TERMCAP_me
LESS_TERMCAP_se=$(printf "\e[0m") # leave standout mode
export LESS_TERMCAP_se
LESS_TERMCAP_so=$(printf "\e[01;33m") # enter standout mode(bold yellow)
export LESS_TERMCAP_so
LESS_TERMCAP_ue=$(printf "\e[0m") # leave underline mode
export LESS_TERMCAP_ue
LESS_TERMCAP_us=$(printf '\e[04;38;5;200m') # enter underline mode
export LESS_TERMCAP_us

# See https://bbs.archlinux.org/viewtopic.php?id=287185 for explanation
export GROFF_NO_SGR=1
# export MANROFFOPT=-c

# Show percentage of page completion for man pages
export MANPAGER='/usr/bin/less -s -M +Gg'
# Remove "(press h for help..." message
export MANLESS="\ Manual\ page\ \$MAN_PN\ %lt/%L %pB\%"

# FZF configuration

# Set the fzf display layout
export FZF_DEFAULT_OPTS=" \
  --multi \
  --height=50% \
  --margin=5%,2%,2%,5% \
  --reverse \
  --preview='(highlight -O ansi {} || bat {}) 2> /dev/null | head -n 50' \
  --preview-window=45%,border-double --border=double \
  --prompt='▶' \
  --pointer='→' \
  --marker='✗' \
  --header='CTRL-c or ESC to quit' \
  --color='dark,fg:magenta,border:cyan'"

# Set the fzf default command
export FZF_DEFAULT_COMMAND='rg --files --hidden --glob "!.cache,.git,.ssh,.npm,.vscode,__pycache__,bundle,.mozilla,.ipython,.pip-audit-cache,.yarn,storage,storage2,tmp,bundle,po,htmlcov,staticfiles,migrations,"'

# Set up fzf key bindings and fuzzy completion
# shellcheck source=/dev/null
source <(fzf --zsh)

# Check ssh-agent and add keys.
if [ ! -S ~/.ssh/ssh_auth_sock ]; then
    eval "$(ssh-agent)"
        ln -sf "$SSH_AUTH_SOCK" ~/.ssh/ssh_auth_sock
fi

export SSH_AUTH_SOCK=~/.ssh/ssh_auth_sock
ssh-add -l > /dev/null || ssh-add ~/.ssh/abulafia_key_2027

# set GPG agent to point to TTY
GPG_TTY=$(tty)
export GPG_TTY

# Python Poetry keyring unlock issue
# https://github.com/python-poetry/poetry/issues/1917#issuecomment-1235998997
# may also want to try "poetry config keyring.enabled false"
# export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring

# Personal aliases
# NOTE: As of 20260705: aliases are maintained in $ZSH_CUSTOM/aliases.zsh
# [ -f ~/.oh-my-zsh/custom/aliases.zsh ] && source ~/.oh-my-zsh/custom/aliases.zsh
if [ -f "$ZSH_CUSTOM/aliases.zsh" ]; then
    source "$ZSH_CUSTOM/aliases.zsh"
fi
#
# https://blog.askesis.pl/post/2017/04/how-to-debug-zsh-startup-time.html
# zprof
