#
# ~/.bash_profile
#
#  Version: 0.0.2
#  Modified: 20220922

[[ -f ~/.bashrc ]] && . ~/.bashrc
export GPG_TTY=$(tty)

# Added pyenv - 20220922
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
