#
# ~/.bash_profile
#
#  Version: 0.0.2
#  Modified: 20221128

[[ -f ~/.bashrc ]] && . ~/.bashrc
export GPG_TTY=$(tty)
. "$HOME/.cargo/env"

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
